
export const TOGGLE_NIGHT_MODE = 'TOGGLE_NIGHT_MODE';

export const ONLINE = "ONLINE";
export const OFFLINE = 'OFFLINE';

export const UPDATE_PROFILE = "UPDATE_PROFILE";


export const LOADING = 'LOADING';
export const GENERATE_RESPONSE = 'GENERATE_RESPONSE';
export const UPDATE_RESPONSE = 'GENERATE_RESPONSE';
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE';
export const START_TYPING = 'START_TYPING';
export const STOP_TYPING = 'STOP_TYPING';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const START_DELAY = 'START_DELAY';
export const STOP_DELAY = 'STOP_DELAY';
export const UPDATE_DB = 'UPDATE_DB';
export const RESET_DB = 'RESET_DB';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const BABY_CHET_MODE = 'BABY_CHET_MODE';
export const HANDLE_INPUT_ERROR = 'HANDLE_INPUT_ERROR';
export const CLEAR_INPUT_ERROR = 'CLEAR_INPUT_ERROR';

export const FETCH_CHET_PHRASES = 'FETCH_PHRASES';
export const FETCH_BABYCHET_PHRASES = 'FETCH_BABYCHET_PHRASES';

export const UPDATE_CHET_PHRASES = "UPDATE_CHET_PHRASES";
export const UPDATE_BABYCHET_PHRASES = "UPDATE_BABYCHET_PHRASES";

export const SAVE_CHAT = 'SAVE_CHAT';
export const CLEAR_CHAT = 'CLEAR_CHAT';